### ISSUE TITLE
Can't get it working on Vue Nuxt app

### ISSUE THREAD

**Issue by shanewmurphy** [jairoblatt/vue-material-tabs#11]
Firstly I'm not a developer. 

Here are the steps I've taken to implement vue-material-tabs using nuxt app

 1. npm install --save vue-material-tabs
 2. Create a file called "vue-material-tabs.js" in the plugin folder and added 
 `import Vue from 'vue';
  import Tabs from 'vue-material-tabs';

  Vue.use(Tabs);`

3. Registered the plugin in nuxt.config.js like so `plugins: ['~/plugins/vue-material-tabs.js']`
4. index.vue `<script>
          import Tabs from "vue-material-tabs";
          export default {
          components: {
          tabs,
          tabItem,
    },
  };

</script>`

5. 
![Screenshot 2021-06-03 at 12 50 49](https://user-images.githubusercontent.com/3694619/120647258-4fdafe80-c472-11eb-9a6e-4e2544df1247.png)

6. Browser localhost: 
![Screenshot 2021-06-03 at 13 48 55](https://user-images.githubusercontent.com/3694619/120647373-71d48100-c472-11eb-8a1f-1bc7fbf7b0ce.png)

**Comment by shanewmurphy** [comment]
Got it working!!

**Comment by jairoblatt** [comment]
Great, for now we do not have support for ssr, you can import how an global component in your nuxt.config using the mode client as 
```javascript
plugins:[{
    src: '@/plugins/vue-material-tabs',
    mode: 'client'
  }]
```
Or you can use it in your local component with the <client-only> component provided by nuxt
https://nuxtjs.org/docs/2.x/features/nuxt-components#the-client-only-component
```html
<client-only> <Tabs>....</Tabs> </client-only>
```

**Comment by shanewmurphy** [comment]
Honestly, I'm sorry I came across your tabs! I've implemented it BUT I don't understand how to get it to work responsively. There's NO response to the tabs when viewed at small screens.
