### ISSUE TITLE
Adding content to each tab

### ISSUE THREAD

**Issue by shanewmurphy** [jairoblatt/vue-material-tabs#12]
Sorry, I'm not a developer. I'm trying to add content for each tab

I have tabs working fine in vue nuxt application

` <Tabs>
          <TabItem name="Foo">
            <div class="first-tab">First tab</div>
          </TabItem>
          <TabItem name="Bar">
            <div class="second-tab">Second tab</div>
          </TabItem>
        </Tabs>`

How do add content for each tab? like -
![Screenshot 2021-06-03 at 14 22 42](https://user-images.githubusercontent.com/3694619/120652985-2de47a80-c478-11eb-80db-b38a933d61fa.png)

**Comment by jairoblatt** [comment]
All content must be in the TabItem component which is wrapped in the Tab component.

You can see a demo application here
https://github.com/jairoblatt/vue-material-tabs/blob/master/demo/src/App.vue

Like this
```html
<Tab>
 <TabItem name="my first tab">
  <p>
   ...your content here
  </p
 </TabItem>

 <TabItem name="my second tab">
    <MyCustomComponent/>
 <TabItem>
</Tab>
```

**Comment by shanewmurphy** [comment]
Thanks for getting back to me so soon. 

I guess I'm out of my depth here regarding knowledge of Vue but I did manage to get bootstrap working in my app BUT their Tabs component is not responsive enough and that's why wish to use your Tabs. 

I've copied your demo example and is working on my app but your tab example is too dynamic i.e 

Don't understand why there are 9 tabs?

I just wanna hard code the Tabs Content (TabItem) for each one individually. 

Anyway thanks for replying back! 

![Screenshot 2021-06-03 at 18 19 26](https://user-images.githubusercontent.com/3694619/120685872-45cbf680-c498-11eb-9454-dbfebbef1d4e.png)

**Comment by shanewmurphy** [comment]
Sorry again but I think understand (kinda) now 

I've removed 
`<TabItem v-for="i in add" :key="`tab-${i}`" :name="`tab ${i}`" :disabled="disabled && i === 2">`

To be just: <TabItem name="Tab title">...content for each goes here</TabItem>

Thanks again
