### ISSUE TITLE
cdn or unpkg  

### ISSUE THREAD

**Issue by amchconsult** [jairoblatt/vue-material-tabs#14]
Hi, 
I am trying to use it with CDN or unpkg for a global project and it is not working.

vue-material-tabs.min.js:1 Uncaught ReferenceError: require is not defined
    at vue-material-tabs.min.js:1
    at vue-material-tabs.min.js:1
(anonymous) @ vue-material-tabs.min.js:1
(anonymous) @ vue-material-tabs.min.js:1

thank you

**Comment by jairoblatt** [comment]
Hi,
Thanks for report, please update your package to version v0.1.4 and tell me if it still doesn't work for you.

Thanks.

**Comment by amchconsult** [comment]
Hey, Thank you for your prompt reply.
I can't make it work.
I am using 

Vue.use(VueMaterialTabs);

```
<Tabs v-model="active_tab">
  <TabItem name="tab1">
    <div class="first-tab">First tab</div>
  </TabItem>
  <TabItem name="tab2">
    <div class="second-tab">Second tab</div>
  </TabItem>
</Tabs>
```

**Comment by amchconsult** [comment]
codepen test link

https://codepen.io/alecode_13/pen/jOBgOoM
