### ISSUE TITLE
Stubborn font

### ISSUE THREAD

**Issue by draynur** [jairoblatt/vue-material-tabs#18]
Is there a way to override the default font for the navigation tabs located [here](https://github.com/jairoblatt/vue-material-tabs/blob/cfe8f5a46704fb2da2ed0b6726fafe2983826ff7/demo/src/App.vue#L152). I love the simplicity of the component, but I can't use it unless I find a better way to override this styling. Thanks!

**Comment by jairoblatt** [comment]
Hey, thanks for report, the components don't have default any font, what that you showed me in the issue is just demo app.

**Comment by draynur** [comment]
Whoops 😆, my problem was elsewhere and I solved it as well. Thanks for the reply!
