### ISSUE TITLE
How to Programmatically Navigate to a Given Tab, Re breaking changes in recent version

### ISSUE THREAD

**Issue by Lissy93** [jairoblatt/vue-material-tabs#19]
Hiya,
Thanks for developing and maintaining this project - very nice component! 😄 

I've had a couple of issues, [upgrading](https://github.com/Lissy93/dashy/pull/81) to to the latest version versions (`0.1.5`), as v `0.1.3` included some breaking changes  which broke some styling and functionality in my app. 

I've got most of it working again, but the only thing I cannot figure out still, is how to programmatically navigate to a given tab.
In previous versions, I did it like this:

```javascript
goToTabByIndex(tabIndex) {
  const tabToSelect = this.$refs.tabView.navItems[tabIndex];
  this.$refs.tabView.activeTabItem({ tabItem: tabToSelect, byUser: true });
},
```

I know not the neatest solution, and that's probably why it no longer works in the current version - any ideas of the correct approach to implement this with your updated component?

Thank you :)

**Comment by Lissy93** [comment]
Another small suggestion, maybe going forward, any structural modifications which may include breaking changes have their major version bumped, instead of minor version? 
As traditionally any change in the second or third digit of version numbers (of [npm modules](https://docs.npmjs.com/about-semantic-versioning)) indicates that the package is fully backwards compatible.

**Comment by jairoblatt** [comment]
Hi @Lissy93, The method "activeTabItem" was refactored in the version  0.1.4, It's now accepted as a parameter only "tabItem"

See if this work for you.
```js
goToTabByIndex(tabIndex) {
  const tabToSelect = this.$refs.tabView.navItems[tabIndex];
  // this.$refs.tabView.activeTabItem({ tabItem: tabToSelect, byUser: true });
 this.$refs.tabView.activeTabItem(tabToSelect);
},
```

And thanks for the tip, i will follow the next time.

**Comment by Lissy93** [comment]
Awesome, thank you very much @jairoblatt! This is now working :)
