### ISSUE TITLE
Error on hot reload

### ISSUE THREAD

**Issue by nadav-letsapp** [jairoblatt/vue-material-tabs#34]
**Using in nuxt**
error:
**Cannot read properties of undefined (reading 'model')
at vue-material-tabs.esm.js:929**

every time there is hot reload error appeared and sometimes when switching between routes.
the function with the problem:

findIndexTab(tab) {
return this.tabItems.findIndex(el => el.model == tab.model);
}

stack start from 

  beforeDestroy() {
    this.$parent.unRegister(this);
  },

**Comment by jairoblatt** [comment]
Thanks for report, Please update your package to `vue-material-tabs@1.1.1`. This was fixed.
